[build-system]
requires = [
    "setuptools>=61.0",
    'selenium>=4.7.2',
    'undetected-chromedriver>=3.1.7'
]
build-backend = "setuptools.build_meta"

authors = [
  { name="Ugur Sahin", email="ugorsahin@tutanota.de"},
]

[project]
name = "chatgpt_automation"
description = "A Headless Chrome interface to communicate with ChatGPT"
readme = "README.md"
requires-python = ">=3.8"
version = "0.1.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]