version: 2.1
orbs:
  python: circleci/python@2.0.3
  browser-tools: circleci/browser-tools@1.4.6
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.4
    resource_class: talkingheads/localservers
    steps:
      - checkout
      - browser-tools/install-chrome
      - run:
          command: |
            google-chrome --version
          name: Check install
      - run:
          name: Install talkingheads and pytest
          command: |
            python -m pip install .
            python -m pip install pytest
      - run:
          name: Run tests
          command: python -m pytest
      - store_test_results:
          path: talkinghead-results
workflows:
  base-tests:
    jobs:
      - build-and-test
